### ISSUE TITLE
Need to handle bad connection/process launching for tool integration tests

### ISSUE THREAD

**Issue by chipsenkbeil** [ensime/scala-debugger#294]
API tests use the launching debugger, which seems to handle starting a process and connecting to it well.

The tool tests use the attaching debugger combined with starting a process manually, which seems to have occasional hiccups where either the process died early or there's a race condition on reaching the preset breakpoints. An example of the log seen is below.

Maybe spawning a process needs to support a retry option (if we can even detect if there is an issue). Need to understand exactly what is happening in terms of the process (store the log, maybe?) and the test itself.

```
Exception in thread "Thread-131" com.sun.jdi.VMDisconnectedException: connection is closed
	at com.sun.tools.jdi.TargetVM.send(TargetVM.java:293)
	at com.sun.tools.jdi.VirtualMachineImpl.sendToTarget(VirtualMachineImpl.java:1032)
	at com.sun.tools.jdi.PacketStream.send(PacketStream.java:59)
	at com.sun.tools.jdi.JDWP$VirtualMachine$Dispose.enqueueCommand(JDWP.java:439)
	at com.sun.tools.jdi.JDWP$VirtualMachine$Dispose.process(JDWP.java:430)
	at com.sun.tools.jdi.VirtualMachineImpl.dispose(VirtualMachineImpl.java:555)
	at org.scaladebugger.api.debuggers.AttachingDebugger$$anonfun$stop$3.apply(AttachingDebugger.scala:149)
	at org.scaladebugger.api.debuggers.AttachingDebugger$$anonfun$stop$3.apply(AttachingDebugger.scala:149)
	at scala.Option.foreach(Option.scala:236)
	at org.scaladebugger.api.debuggers.AttachingDebugger.stop(AttachingDebugger.scala:149)
	at org.scaladebugger.tool.backend.StateManager$$anonfun$clearActiveDebugger$1.apply(StateManager.scala:54)
	at org.scaladebugger.tool.backend.StateManager$$anonfun$clearActiveDebugger$1.apply(StateManager.scala:54)
	at scala.Option.foreach(Option.scala:236)
	at org.scaladebugger.tool.backend.StateManager.clearActiveDebugger(StateManager.scala:54)
	at org.scaladebugger.tool.backend.StateManager.clear(StateManager.scala:20)
	at org.scaladebugger.tool.Repl$$anon$1.run(Repl.scala:55)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by chipsenkbeil** [comment]
Going to close this issue. Java processes have a lot of limitations. The frequent dead process problem during testing has been isolated and fixed.
